### ISSUE TITLE
My hubconnection is not stopping

### ISSUE THREAD

**Issue by Katekko** [jamiewest/signalr_core#11]
![image](https://user-images.githubusercontent.com/13632735/80313701-0c1fbb00-87c3-11ea-9a69-20435cb19866.png)

![image](https://user-images.githubusercontent.com/13632735/80313695-01652600-87c3-11ea-9ad4-dc9c6c89c187.png)

I'm trying stop my hub connection after logout
![image](https://user-images.githubusercontent.com/13632735/80313707-1d68c780-87c3-11ea-8bd1-ea542be60a51.png)

But the stop is not working. The code stuck on "await con.stop()" forever

ed1:
It will be stuck on disconnecting forever, I will create another connection, but the stop method should be working, right?
![image](https://user-images.githubusercontent.com/13632735/80313785-a08a1d80-87c3-11ea-8c69-4090d1f715b7.png)

**Comment by jamiewest** [comment]
I fixed this in a recent [PR](https://github.com/jamiewest/signalr_core/commit/15daf04ec8cdf92bc463074826ac10cc76fbf872#diff-93a20c9634d2a16fef7e80be6b0574d8R779). I am waiting on publishing because of the current code base relies on a [PR](https://github.com/dart-lang/http/pull/388) for the `http` package. As soon as they publish I will push this out.

**Comment by Katekko** [comment]
![image](https://user-images.githubusercontent.com/13632735/80384859-cb37ad00-887b-11ea-9e30-217bf22b38a4.png)

Is that means the packge was already published?

**Comment by jamiewest** [comment]
The package was just published today, which means I was able to publish mine. Upgrade your version for `signalr_core` to `1.0.3`. Please file an issue if you encounter problems. Thank you!
